/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package OntoUML.validation;

import OntoUML.Association;
import OntoUML.DirectedBinaryRelationship;
import OntoUML.Property;
import OntoUML.Type;

/**
 * A sample validator interface for {@link OntoUML.Property}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyValidator {
	boolean validate();

	boolean validateIsDerived(boolean value);
	boolean validateIsReadOnly(boolean value);
	boolean validateIsNavigable(boolean value);
	boolean validateEndType(Type value);
	boolean validateAssociationEnd(Association value);
	boolean validateSource(DirectedBinaryRelationship value);
	boolean validateTarget(DirectedBinaryRelationship value);
	boolean validateAux(Property value);
}
